###buttons###

#X button#
bool x_button_pressed false

#Y button#
bool y_button_pressed false

#A button#
bool a_button_pressed false

#B button#
bool b_button_pressed false


###triggers and bumpers###

#left trigger#
float64 left_trigger_pressed 0.0

#right trigger#
float64 right_trigger_pressed 0.0

#LB trigger#
bool left_bumper_pressed false

#RB trigger#
bool right_bumper_pressed false

###directional pads###

#d-pad down#
bool d_pad_down_pressed false

#d-pad up#
bool d_pad_up_pressed false

#d-pad left#
bool d_pad_left_pressed false

#d-pad right#
bool d_pad_right_pressed false

###analog sticks###

#left stick pressed#
bool left_stick_pressed false

#right stick pressed#
bool right_stick_pressed false

#right stick#
StickPosition left_stick

#left stick#
StickPosition right_stick


### center buttons ###

#back button#
bool back_pressed false
#start button#
bool start_pressed false


#Max Trigger Value
float64 MAX_TRIGGER_VALUE = 1.0
